const systems=[
{id:'dalux',n:'Dalux',d:'Drawings, tasks & inspections',u:'https://www.dalux.com/'},
{id:'projectwise',n:'ProjectWise',d:'Project documents & information',u:'https://www.bentley.com/software/projectwise/'},
{id:'powerbi',n:'Power BI',d:'Project dashboards & reporting',u:'https://app.powerbi.com/'},
{id:'acc',n:'Autodesk Construction Cloud',d:'Documents, coordination & workflows',u:'https://construction.autodesk.com/'},
{id:'aconex',n:'Aconex',d:'Project information & correspondence',u:'https://www.oracle.com/construction-engineering/aconex/'},
{id:'fme',n:'FME',d:'Data transformation & automation',u:'https://www.safe.com/'}];
function recent(){let a=[];try{a=JSON.parse(localStorage.hubRecent||'[]')}catch{};return (a.map(id=>systems.find(s=>s.id===id)).filter(Boolean).length? a.map(id=>systems.find(s=>s.id===id)).filter(Boolean):systems.slice(0,3))}
function openSys(id){let s=systems.find(x=>x.id===id);let a=recent().map(x=>x.id).filter(x=>x!==id);a.unshift(id);localStorage.hubRecent=JSON.stringify(a.slice(0,3));location.href=s.u}
function card(s){return `<article class="card"><div class="icon">${s.n[0]}</div><div class="copy"><strong>${s.n}</strong><span>${s.d}</span></div><button class="open" onclick="openSys('${s.id}')">Open</button></article>`}
function home(){let r=recent();return `<section class="hero"><div class="eyebrow">Lower Thames Crossing · Digital</div><h1>Everything digital,<br>in one place.</h1><p>Quick access to the systems, training and support you need on the project.</p></section><section class="section"><div class="head"><h2>Quick access</h2><button class="link" onclick="go('systems')">All systems →</button></div><div class="systems">${r.map(card).join('')}</div></section><section class="section"><h2 style="margin-bottom:12px">Need something else?</h2><div class="tiles"><button class="tile" onclick="go('training')"><i>▶</i><strong>Training</strong><span>Short guides and tutorials</span></button><button class="tile" onclick="go('help')"><i>?</i><strong>Digital help</strong><span>Get support or report an issue</span></button><button class="tile" onclick="go('systems')"><i>▦</i><strong>All systems</strong><span>See the complete project list</span></button></div></section>`}
function systemsPage(){return `<section class="page"><button class="back" onclick="go('home')">← Home</button><div class="eyebrow">Project systems</div><h1>Apps & Systems</h1><p>Simple access to the digital tools used on the project.</p><div class="systems" style="margin-top:18px">${systems.map(card).join('')}</div></section>`}
function training(){return `<section class="page"><button class="back" onclick="go('home')">← Home</button><div class="eyebrow">Learn</div><h1>Training</h1><p>Short, practical guides for the tools you use.</p>${[['Dalux basics','Finding drawings, tasks and information.'],['Digital Hub basics','Finding systems and digital support.'],['Power BI essentials','Using project dashboards effectively.']].map(x=>`<article class="list"><h3>${x[0]}</h3><p>${x[1]}</p><button class="primary" onclick="alert('Training content will be linked here.')">Coming soon</button></article>`).join('')}</section>`}
function help(){return `<section class="page"><button class="back" onclick="go('home')">← Home</button><div class="eyebrow">Support</div><h1>Digital help</h1><p>Having trouble with a project system? Start here.</p><div class="notice"><b>For urgent site issues</b><br>Use the normal project IT / site support route.</div><article class="list"><h3>IT Helpdesk</h3><p>Accounts, devices, access and technical issues.</p><button class="primary" onclick="alert('Replace with the project IT helpdesk URL.')">Contact IT</button></article><article class="list"><h3>Digital Team</h3><p>Systems, workflows, dashboards and digital improvement.</p><button class="primary" onclick="alert('Replace with the Digital Team contact route.')">Contact Digital</button></article></section>`}
function go(r){let v={home,systems:systemsPage,training,help}[r]||home;document.getElementById('view').innerHTML=v();scrollTo(0,0);history.replaceState({},'',`#${r}`)}
go(location.hash.slice(1)||'home');